package
{
   import mx.resources.ResourceBundle;
   
   public class en_US$OptionsConfigurationWidget_properties extends ResourceBundle
   {
       
      public function en_US$OptionsConfigurationWidget_properties()
      {
         super("en_US","OptionsConfigurationWidget");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "IMPORTEXPORT_MINIMAP_DLG_EXPORT_PROGRESS_TITLE":"Information",
            "IMPORTEXPORT_MINIMAP_DLG_EXPORT_FAIL_TITLE":"Error!",
            "IGNORE_FILTEREDITOR_LBL_PATTERN_COLUMN":"Name",
            "HOTKEY_DLG_RESET_TITLE":"Attention!",
            "HOTKEY_DLG_ADD_NEW_SET":"New Set",
            "MESSAGE_DLG_RESET_TEXT":"Are you sure that you want to reset all message options to their respective default values?",
            "IMPORTEXPORT_OPTIONS_DLG_EXPORT_FAIL_TEXT":"The options could not be exported.",
            "IMPORTEXPORT_ERROR_DLG_READ_TEXT":"Cannot open the file for reading.",
            "RENDERER_PERF_HEADING":"Frame Rate",
            "HOTKEY_DLG_REMOVE_TEXT":"Do you really want to remove the set \"{0}\"? All actions and hotkeys will be lost.",
            "HOTKEY_DLG_EDIT_STATIC":"The hotkey is already assigned to \"{0}\". This assignment cannot be changed.",
            "IMPORTEXPORT_OPTIONS_RESET":"Reset Options",
            "IMPORTEXPORT_MINIMAP_DLG_EXPORT_SAVE_TEXT":"Export complete. Do you want to save the minimap now?",
            "HOTKEY_DLG_EDIT_CLEAR":" Click \"Clear\" to remove the hotkey from \"{0}\".",
            "RENDERER_LIGHT_HEADING":"Light",
            "IMPORTEXPORT_MINIMAP_DLG_IMPORT_PROGRESS_TEXT":"Please wait while the minimap is being imported ({0}% done). If you cancel this process, your minimap may be incomplete. If this happens, you can always import the same file again.",
            "IGNORE_FILTEREDITOR_LBL_EMPTY_PATTERN":"<empty>",
            "IMPORTEXPORT_MINIMAP_DLG_EXPORT_SAVE_TITLE":"Information",
            "IGNORE_LBL_WHITE_LIST_GLOBAL":"Global options for allowing messages:",
            "HOTKEY_DLG_REMOVE_TITLE":"Attention!",
            "IMPORTEXPORT_MINIMAP_DLG_IMPORT_FAIL_TEXT":"The minimap could not be imported.",
            "IMPORTEXPORT_ERROR_DLG_WRITE_TITLE":"Error!",
            "STATUS_CREATURE_NAME":"Show Name",
            "STATUS_LABEL":"Status",
            "STATUS_PLAYER_NAME":"Show Name",
            "IMPORTEXPORT_OPTIONS_HEADING":"Options",
            "RENDERER_LIGHT_LEVEL_SEPARATOR":"Level Separator",
            "HOTKEY_MODE_CHATMODEOFF":"Chat Off",
            "IMPORTEXPORT_OPTIONS_DLG_EXPORT_FAIL_TITLE":"Error!",
            "HOTKEY_DLG_ADD_TEXT":"Please choose the set you want to copy or select \"{0}\" to create a new set using the default settings.",
            "IMPORTEXPORT_MINIMAP_DLG_IMPORT_FAIL_TITLE":"Error!",
            "IGNORE_LBL_IGNORE_LIST_GLOBAL":"Global options for ignoring messages:",
            "GENERAL_GENERAL_HEADING":"General",
            "IMPORTEXPORT_MINIMAP_EXPORT":"Export Minimap",
            "IMPORTEXPORT_MINIMAP_DLG_EXPORT_PROGRESS_TEXT":"Please wait while the minimap is being exported ({0}% done).",
            "RENDERER_MAP_HEADING":"Game Window",
            "RENDERER_LIGHT_AMBIENT_BRIGHTNESS":"Ambient Brightness",
            "HOTKEY_DLG_RESET_TEXT":"Are you sure that you want to reset all bindings in the mode \"{0}\" of the set \"{1}\"?",
            "STATUS_WIDGET_STYLE":"Style",
            "IGNORE_LABEL":"Ignore List",
            "STATUS_CREATURE_FLAGS":"Show Marks",
            "IGNORE_FILTEREDITOR_BTN_ADD":"Add",
            "GENERAL_COMBAT_AUTOCHASEOFF":"Auto Chase Off",
            "MESSAGE_DEFAULT_SET_NAME":"Set {0}",
            "MESSAGE_COLUMN_COLOUR":"Colour",
            "MESSAGE_CONSOLE_TIMESTAMPS":"Show Timestamps",
            "HOTKEY_DLG_EDIT_SELF":"The hotkey is already assigned to \"{0}\". You annot assign the same hotkey twice.",
            "RENDERER_LIGHT_ENABLED":"Enable Light",
            "HOTKEY_DLG_ADD_TITLE":"Add Hotkey Set  ",
            "IMPORTEXPORT_OPTIONS_IMPORT":"Import Options",
            "HOTKEY_MODE":"Mode",
            "IMPORTEXPORT_MINIMAP_DLG_EXPORT_FAIL_TEXT":"The minimap could not be exported.",
            "RENDERER_PERF_SHOW_FPS":"Show Frame Rate",
            "IMPORTEXPORT_OPTIONS_DLG_IMPORT_FAIL_TITLE":"Error!",
            "IGNORE_CHECK_IGNORE_LIST_PRIVATE":"Ignore Private Messages",
            "IGNORE_LBL_IGNORE_LIST_CHARACTERS":"Characters you wish to ignore:",
            "HOTKEY_COLUMN_SECOND_BINDING":"Second Key",
            "IGNORE_LBL_WHITE_LIST_CHARACTERS":"Characters you allow to message you:",
            "HOTKEY_COLUMN_ACTION":"Action",
            "IMPORTEXPORT_ERROR_DLG_READ_TITLE":"Error!",
            "STATUS_CREATURE_HEADING":"Other Creatures in Game Window",
            "HOTKEY_SETNAME":"Set",
            "HOTKEY_DLG_EDIT_DEFAULT":"Click \"Okay\" to assign the hotkey.",
            "STATUS_WIDGET_SKILL":"Progress Bar",
            "STATUS_CREATURE_STYLE":"Style",
            "MESSAGE_CONSOLE_LEVELS":"Show Levels",
            "HOTKEY_MODE_CHATMODEON":"Chat On",
            "STATUS_RENDERER_STATUS_STYLE_CLASSIC":"Classic",
            "STATUS_RENDERER_STATUS_STYLE_HUD":"HUD",
            "HOTKEY_ADD_SET":"Add",
            "RENDERER_LABEL":"Graphics",
            "HOTKEY_COLUMN_FIRST_BINDING":"First Key",
            "MESSAGE_COLUMN_CHANNEL":"Chat Console",
            "MESSAGE_COLUMN_ONSCREEN":"Game Window",
            "IMPORTEXPORT_ERROR_DLG_WRITE_TEXT":"Cannot open the file for writing.",
            "IGNORE_CHECK_IGNORE_LIST_YELLING":"Ignore Yelling",
            "RENDERER_PERF_MAX_FPS":"Maximum Frame Rate",
            "HOTKEY_DLG_EDIT_TITLE":"Edit Hotkey for \"{0}\"",
            "STATUS_PLAYER_FLAGS":"Show Marks",
            "RENDERER_MAP_SCALE":"Scale Game Window",
            "STATUS_WIDGET_HEADING":"Status Bar",
            "STATUS_PLAYER_HEADING":"Own Character in Game Window",
            "IMPORTEXPORT_OPTIONS_EXPORT":"Export Options",
            "HOTKEY_RESET_MAPPING":"Restore Defaults",
            "IMPORTEXPORT_ERROR_DLG_CONCURRENT_TITLE":"Error!",
            "HOTKEY_REMOVE_SET":"Remove",
            "MESSAGE_GENERAL_RESET":"Restore Defaults",
            "GENERAL_COMBAT_HEADING":"Combat",
            "TITLE":"Options",
            "STATUS_CREATURE_HEALTH":"Show Health",
            "STATUS_RENDERER_STATUS_STYLE_OFF":"Disabled",
            "IMPORTEXPORT_OPTIONS_DLG_IMPORT_FAIL_TEXT":"The options contained errors and were not imported.",
            "IMPORTEXPORT_LABEL":"Import/Export",
            "MESSAGE_DLG_RESET_TITLE":"Attention!",
            "IMPORTEXPORT_OPTIONS_DLG_RESET_TITLE":"Please Confirm!",
            "MESSAGE_LABEL":"Messages",
            "IMPORTEXPORT_MINIMAP_IMPORT":"Import Minimap",
            "HOTKEY_LABEL":"Hotkeys",
            "HOTKEY_DLG_ADD_DEFAULT_SET":"<default>",
            "GENERAL_LABEL":"General",
            "HOTKEY_BINDING_EMPTY":"<empty>",
            "IMPORTEXPORT_MINIMAP_HEADING":"Minimap",
            "IMPORTEXPORT_ERROR_DLG_CONCURRENT_TEXT":"Another file browse dialog is still open. Please close the dialog and try again.",
            "IMPORTEXPORT_OPTIONS_DLG_RESET_TEXT":"Do you really want to reset all options to their default values?",
            "IGNORE_CHECK_WHITE_LIST_ACTIVE":"Activate White List",
            "MESSAGE_COLUMN_MODE":"Message",
            "STATUS_PLAYER_STYLE":"Style",
            "IGNORE_FILTEREDITOR_LBL_PERMANENT_COLUMN":"",
            "IGNORE_CHECK_IGNORE_LIST_ACTIVE":"Activate Ignore List",
            "STATUS_PLAYER_HEALTH":"Show Health",
            "HOTKEY_DLG_EDIT_DYNAMIC":"The hotkey is already assigned to \"{0}\". Click \"Okay\" to assign it to \"{1}\" instead.",
            "IGNORE_CHECK_WHITE_LIST_BUDDY":"Allow VIPs to message you",
            "GENERAL_GENERAL_CLASSIC_CONTROLS":"Tibia Classic Controls",
            "IMPORTEXPORT_MINIMAP_DLG_IMPORT_PROGRESS_TITLE":"Information",
            "IGNORE_FILTEREDITOR_BTN_DEL":"Remove",
            "STATUS_PLAYER_MANA":"Show Mana"
         };
         return _loc1_;
      }
   }
}
